version: '3'
services:
  mysql-master:
    image: mysql:5.7
    ports: 
    - "3306:3306"
    volumes:
    - ./data-master:/var/lib/mysql
    - ./etc/mysql-master:/etc/mysql/conf.d/
    environment:
      MYSQL_ROOT_PASSWORD: a.123456
    networks:
    - public-network
  mysql-slave:
    image: mysql:5.7
    ports: 
    - "3307:3306"
    volumes:
    - ./data-slave:/var/lib/mysql
    - ./etc/mysql-slave:/etc/mysql/conf.d/
    environment:
      MYSQL_ROOT_PASSWORD: a.123456
    networks:
    - public-network
networks:
    public-network:
